### ISSUE TITLE
Add support for Tx only mode?

### ISSUE THREAD

**Issue by jcwren** [bonezegei/Bonezegei_SoftSerial#1]
The library has a constructor for receive-only operation, so would it be possible for you to add a constructor for transmit-only operation? Perhaps by using the RX + TX constructor, but passing -1 as the RX pin number? If you were to add that capability, it would add consistency to support specifying -1 as the TX pin for receive-only operation also.

**Comment by bonezegei** [comment]
I appreciate your suggestion; I've already implemented that code today.
